### ISSUE TITLE
Enable GZIP compression

### ISSUE THREAD

**Issue by ppi-buck** [dockerwest/nginx-pimcore5#1]
Hey ;-) 

how do I enable gzip compression for my nginx? 
I found the config is already in your file structure https://github.com/dockerwest/nginx-pimcore5/blob/master/stable/scripts/etc/nginx/conf.d/00_gzip.conf but how do I enable it? 

GTmetrix and checkgzipcompression.com tell me it's not enabled. 

I bet it's only a very little thing I'm missing (again).

Thanks

**Comment by BlackIkeEagle** [comment]
Its enabled automatically for the given mime types, so in general for the static files, I guess you are testing on html? that is not enabled by default

**Comment by ppi-buck** [comment]
I'm testing with GTmetrix and I'm getting this result:

> Enable compression for the following resources to reduce their transfer size by 301.9KiB (81% reduction).
> 
> Compressing https://example.com/cache-buster-1531726796/static/dist/css/bo.css could save 183.2KiB (87% reduction).
> Compressing https://example.com/cache-buster-1531726795/static/dist/assets/swiper.min.js could save 88.2KiB (74% reduction).
> Compressing https://example.com/ could save 14.6KiB (76% reduction).
> Compressing https://example.com/cache-buster-1531726801/static/dist/js/bo.js could save 8.1KiB (66% reduction).
> Compressing https://example.com/cache-buster-1531726795/static/dist/assets/baguetteBox.min.js could save 5.6KiB (62% reduction).
> Compressing https://example.com/static/dist/img/TemplateOne/menu-closed.svg could save 1.3KiB (63% reduction).
> Compressing https://example.com/static/dist/img/TemplateOne/menu-opened.svg could save 919B (56% reduction).


Doesn't seem to have gzip enabled for MIME-Types like SVG, CSS and JS like it should looking at your config.

**Comment by BlackIkeEagle** [comment]
Maybe the proper headers are not sent to nginx.

out of the box, html, css, js and svg work here

![deepinscreenshot_select-area_20180716101743](https://user-images.githubusercontent.com/293691/42748809-c66a9fbc-88e1-11e8-8a78-8ea5355239ac.png)
![deepinscreenshot_select-area_20180716101758](https://user-images.githubusercontent.com/293691/42748810-c690c9da-88e1-11e8-91eb-e65cbc95c641.png)
![deepinscreenshot_select-area_20180716101829](https://user-images.githubusercontent.com/293691/42748811-c6aaa1b6-88e1-11e8-968f-84c5c5ced643.png)
![deepinscreenshot_select-area_20180716101917](https://user-images.githubusercontent.com/293691/42748812-c6c26e18-88e1-11e8-9c79-f19a78cf3cf6.png)

**Comment by BlackIkeEagle** [comment]
is your "test" behind a proxy?

**Comment by ppi-buck** [comment]
I can confirm that my local dev environment of the same site has gzip enabled as well. have to check if my live site is behind a proxy... 

Would that mix things up if so?

**Comment by BlackIkeEagle** [comment]
if your proxy is not passing that the client can accept gzip then nginx will not use gzip

**Comment by ppi-buck** [comment]
As we are on a optimization hunt here... I manually added woff,woff2 and ttf files to have Cache-Control headers like so:

```
# add cache-control header to font files
location ~* \.(ttf|woff|woff2)$ {
    expires 2w;
    add_header Cache-Control "public";
}
```

Maybe you can add them here https://github.com/dockerwest/nginx-pimcore5/blob/master/stable/scripts/etc/nginx/conf.d/default.conf#L52

**Comment by BlackIkeEagle** [comment]
could you open a new ticket for that opimization?

**Comment by BlackIkeEagle** [comment]
is the original gzip issue solved? or discovered to be triggered by an external component?

**Comment by ppi-buck** [comment]
I'm guessing my site is behind a proxy. Will have to check with our admins. Think it's no issue with the compose-environment.

So thanks a lot for helping and sorting this out. 

PS: will open a separate issue for font files.

**Comment by BlackIkeEagle** [comment]
super, thanks
