### ISSUE TITLE
Optimize cache-control headers

### ISSUE THREAD

**Issue by ppi-buck** [dockerwest/nginx-pimcore5#2]
I manually added woff,woff2 and ttf files to have Cache-Control headers like so in my overrides:

```yaml
# add cache-control header to font files
location ~* \.(ttf|woff|woff2)$ {
    expires 2w;
    add_header Cache-Control "public";
}
```

Maybe you can add them here https://github.com/dockerwest/nginx-pimcore5/blob/master/stable/scripts/etc/nginx/conf.d/default.conf#L52

Thanks

**Comment by BlackIkeEagle** [comment]
If you want you can make a PR for this, I'll probably end up doing this change near the end of the week if you don't find the time
