### ISSUE TITLE
Change in Nginx configuration for Pimcore 10

### ISSUE THREAD

**Issue by blowk** [dockerwest/nginx-pimcore5#3]
There are some changes in the Nginx configuration for Pomcore 10. ex root /phpapp/web > /phpapp/public
Is it possible to make a new repo for nginx-pimcore10?

More info can be found on:
[Pimcore 10 - Nginx Configuration](https://pimcore.com/docs/pimcore/10.0/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Nginx_Configuration.html)

If you need help testing this docker container, let me know.

**Comment by BlackIkeEagle** [comment]
you can find nginx for pimcore 10 here: https://github.com/dockerwest/nginx-pimcore10
and the compose setup has also been made pimcore 10 compatible: https://github.com/dockerwest/compose-pimcore

If there are issues related to pimcore 10 file your issues there, hopefully everything works, I just did a very short test to see if the admin works

**Comment by blowk** [comment]
Can you help me with this?
I have problems with the sendmail. I get the following error when the mail function in Pimcore 10.

`supported sendmail command flags "/usr/local/lib/mhsendmail --smtp-addr=mailcatcher:1025"; must be one of "-bs" or "-t" but can include additional flags.`

Normaly Mailhog is used instead of mailcatcher, right?
If you need additional info, let me know.
